// Authored teaching example, not a generated answer or benchmark output.
// Uses the existing atlas's radial nerve learning record. Independent expert review pending.
export const demoSlides=[
`RADIAL NERVE — Follow the course
The radial nerve has root contributions C5–T1 and arises from the posterior cord of the brachial plexus.
It leaves the axilla through the triangular interval with the profunda brachii artery, passes in the radial groove of the humerus, and then pierces the lateral intermuscular septum.
Near the elbow it divides into superficial and deep branches.`,
`RADIAL NERVE — Localize the deficit
Radial nerve lesions can impair wrist and finger extension; the deficit depends on lesion level.
The superficial radial branch carries cutaneous sensation. The deep branch continues as the posterior interosseous nerve and supplies many forearm extensors.
The first dorsal web space is a useful sensory examination area for the radial nerve.`,
`HUMERUS — A clinical relationship
The radial nerve's course along the humeral shaft explains why a humeral shaft fracture can endanger it.
Wrist drop suggests loss of wrist extension, but it does not by itself prove a fracture or identify the exact lesion site.
Localize using the injury history, the pattern of muscle weakness, and sensory findings together.`
];
const q=(question:string,options:string[],correct_index:number,explanations:string[],source_quote:string)=>({question,options,correct_index,explanations,source_quote});
export const demoResults={
1:{explanation:'ابدئي بالمصدر ثم المسار ثم التفرع. يخرج العصب الكعبري من الحبل الخلفي للضفيرة العضدية؛ يسير قرب عظم العضد في الثلم الكعبري قبل أن يصل لمنطقة المرفق. تتبّعيه في الأطلس مع العظم: قرب العصب من العظم علاقة مكانية مهمة، ولا يعني أن كل إصابة عظمية تؤذي العصب.',high_yield:['Root contributions: C5–T1','Posterior cord → radial groove → branches near elbow'],terms:[{term:'Radial groove',meaning:'الثلم الكعبري: الموضع العظمي الذي يمر بجواره العصب خلال مساره على العضد.'},{term:'Posterior cord',meaning:'الحبل الخلفي من الضفيرة العضدية، وهو منشأ العصب في هذه الشريحة.'}],clarifications:[],mechanism:[{label:'من الحبل الخلفي',source_quote:'arises from the posterior cord of the brachial plexus'},{label:'يمر في الثلم الكعبري',source_quote:'passes in the radial groove of the humerus'},{label:'يتفرع قرب المرفق',source_quote:'Near the elbow it divides into superficial and deep branches.'}],questions:[q('أي علاقة تفسر أهمية فحص العصب عند إصابة جسم العضد؟',['مروره في الثلم الكعبري على العضد','نشوؤه من الحبل الخلفي وحده','امتلاكه فرعًا سطحيًا وحده'],0,['تضع هذه العلاقة العصب قرب العظم المصاب.','يحدد هذا منشأه، لكنه لا يفسر وحده القرب من جسم العضد.','وجود الفرع وحده لا يحدد علاقته بجسم العضد.'],'passes in the radial groove of the humerus')],source_quotes:['passes in the radial groove of the humerus']},
2:{explanation:'اربطي الوظيفة بمستوى الإصابة. لا يكفي قول «العصب الكعبري مصاب» لوصف كل العجز المتوقع: إصابة فرع سطحي حسي تختلف عن إصابة فرع يغذي العضلات. اجمعي اختبار الحركة وفحص الحس بدل الاعتماد على علامة واحدة.',high_yield:['مستوى الإصابة يغيّر نمط العجز.','الفرع السطحي حسي؛ الفرع العميق يستمر بوصفه العصب بين العظمي الخلفي.'],terms:[{term:'Extension',meaning:'البسط: الحركة التي تُفحص في الرسغ والأصابع هنا.'},{term:'First dorsal web space',meaning:'المسافة الظهرية الأولى بين الإبهام والسبابة؛ منطقة مفيدة لفحص حس العصب الكعبري.'}],clarifications:[],mechanism:[],questions:[q('أي استنتاج تدعمه الشريحة؟',['كل إصابة كعبرية تعطي النمط نفسه','مستوى الإصابة مهم لتوقع العجز','فحص الحس يغني دائمًا عن فحص الحركة'],1,['الشريحة تصرح بأن العجز يعتمد على المستوى.','صحيح: اختلاف الفروع والوظائف يغيّر نمط العجز.','لا تدعم الشريحة الاستغناء عن فحص الحركة.'],'the deficit depends on lesion level')],source_quotes:['the deficit depends on lesion level']},
3:{explanation:'المنطق هنا احتمالي وليس تشخيصًا تلقائيًا: العلاقة التشريحية تجعل العصب معرضًا للخطر في كسر جسم العضد. أما سقوط الرسغ فيصف فقد البسط؛ لا يخبرنا وحده بسبب الإصابة أو موقعها الدقيق. قارني القصة وتوزيع الضعف والحس للوصول إلى توضع أقوى.',high_yield:['كسر جسم العضد → خطر على العصب الكعبري.','Wrist drop علامة وظيفية وليست إثباتًا للسبب.'],terms:[{term:'Wrist drop',meaning:'سقوط الرسغ نتيجة فقد القدرة على بسطه.'},{term:'Localize',meaning:'تحديد موضع الإصابة من نمط العلامات، وليس من اسم عرض واحد.'}],clarifications:[],mechanism:[{label:'علاقة مكانية بجسم العضد',source_quote:"The radial nerve's course along the humeral shaft explains why a humeral shaft fracture can endanger it."},{label:'قد تتأثر وظيفة البسط',source_quote:'Wrist drop suggests loss of wrist extension'},{label:'نجمع علامات متعددة للتوضع',source_quote:'Localize using the injury history, the pattern of muscle weakness, and sensory findings together.'}],questions:[q('ظهر سقوط الرسغ. ما الاستنتاج الأكثر انضباطًا؟',['يثبت وجود كسر بالعضد','يوحي بفقد البسط ويحتاج توضعًا سريريًا','يثبت قطع العصب بالكامل'],1,['لا تثبت هذه العلامة وحدها وجود كسر.','هذا هو الحد الذي تسمح به الشريحة مع ضرورة جمع بقية العلامات.','لا تحدد العلامة وحدها نوع إصابة العصب أو شدتها.'],'Wrist drop suggests loss of wrist extension, but it does not by itself prove a fracture or identify the exact lesion site.')],source_quotes:['Localize using the injury history, the pattern of muscle weakness, and sensory findings together.']}
};
