'use client';
import { useMemo } from 'react';
import { X,ChevronRight,Search } from 'lucide-react';
import { Command,CommandInput,CommandList,CommandItem,CommandGroup } from '@atlas/components/ui/command';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@atlas/components/ui/select';
import { searchAnatomy,systemLabels,regions,colors } from '@atlas/lib/anatomy';
interface Props {query:string;onQuery:(q:string)=>void;system:string;onSystem:(s:string)=>void;region:string;onRegion:(r:string)=>void;selectedId:string|null;onSelect:(id:string)=>void;}
export default function AnatomySearch({query,onQuery,system,onSystem,region,onRegion,selectedId,onSelect}:Props){
 const results=useMemo(()=>searchAnatomy(query,system,region),[query,system,region]);
 const groups=useMemo(()=>[...new Set(results.map(e=>e.system))].sort((a,b)=>query?0:Object.keys(systemLabels).indexOf(a)-Object.keys(systemLabels).indexOf(b)).map(id=>({id,items:results.filter(e=>e.system===id)})),[results,query]);
 return <Command shouldFilter={false} className="anatomy-command"><div className="search-input-wrap"><CommandInput aria-label="Search all anatomy" placeholder="Search anatomy…" value={query} onValueChange={onQuery}/>{query&&<button className="search-clear" aria-label="Clear anatomy search" onClick={()=>onQuery('')}><X size={16}/></button>}</div>
 <div className="browser-filters"><Select value={region} onValueChange={onRegion}><SelectTrigger aria-label="Anatomical region"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="All regions">All regions</SelectItem>{regions.map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select><Select value={system} onValueChange={onSystem}><SelectTrigger aria-label="Anatomical category"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All anatomy</SelectItem>{Object.entries(systemLabels).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></div>
 <div className="browser-count" role="status" aria-live="polite"><span>{results.length} {query?'matches':'structures'}</span>{(system!=='all'||region!=='All regions')&&<button onClick={()=>{onSystem('all');onRegion('All regions');}}>Clear filters</button>}</div>
 <CommandList className="structure-list" aria-label="Anatomy suggestions">{!results.length&&<div className="empty-search"><Search size={23}/><strong>No matching anatomy</strong><p>Try a shorter name, such as “axill”, or clear the category and region filters.</p></div>}{groups.map(g=><CommandGroup key={g.id} heading={`${systemLabels[g.id]} · ${g.items.length}`}>{g.items.map(e=><CommandItem className={'structure-row '+(e.id===selectedId?'selected':'')} key={e.id} value={e.id} onSelect={()=>onSelect(e.id)}><span className="system-mark" style={{background:colors[e.system]}}/><span><Match text={e.name} query={query}/><small>{e.region}{e.assetIds.length?' · 3D':''}</small></span><ChevronRight size={14}/></CommandItem>)}</CommandGroup>)}</CommandList><div className="browser-footer">Type to narrow · ↑ ↓ to browse · Enter to select</div></Command>;
}
function Match({text,query}:{text:string;query:string}){const start=text.toLowerCase().indexOf(query.trim().toLowerCase());if(!query.trim()||start<0)return <>{text}</>;return <>{text.slice(0,start)}<mark>{text.slice(start,start+query.trim().length)}</mark>{text.slice(start+query.trim().length)}</>;}
