'use client';
import { useState } from 'react';
import { ArrowUpRight,Layers,Info } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger } from '@atlas/components/ui/tabs';
import { boneRelations,boneLandmarks,boneAttachments,bonePatches,landmarkFamily,type BoneMode } from '@atlas/lib/anatomy/study';
import { assets,byId,nameOf } from '@atlas/lib/anatomy';
export default function BoneStudy({boneId,mode,onMode,onSelect}:{boneId:string;mode:BoneMode;onMode:(m:BoneMode)=>void;onSelect:(id:string)=>void}){
 const [kind,setKind]=useState<'both'|'origin'|'insertion'>('both');
 const landmarks=boneLandmarks(boneId),attachments=boneAttachments(boneId).filter(a=>kind==='both'||a.kind===kind);
 const mapped=assets.filter(a=>a.role==='landmark-area'&&a.boneId===boneId);
 const bone=byId.get(boneId)!;
 return <section className="bone-study"><div className="study-title"><Layers size={17}/><span>{bone.name} study</span></div><Tabs value={mode} onValueChange={v=>onMode(v as BoneMode)}><TabsList className="study-segments"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="landmarks">Landmarks</TabsTrigger><TabsTrigger value="attachments">Attachments</TabsTrigger>{(['ligaments','joints','neurovascular','clinical'] as const).map(value=><TabsTrigger key={value} value={value}>{value==='neurovascular'?'Nerves + vessels':value.charAt(0).toUpperCase()+value.slice(1)}</TabsTrigger>)}</TabsList></Tabs>
 {mode==='overview'&&<div className="bone-entry-options"><button onClick={()=>onMode('landmarks')}><span><strong>Bony landmarks</strong><small>{landmarks.length} named regions</small></span><ArrowUpRight size={17}/></button><button onClick={()=>onMode('attachments')}><span><strong>Muscle attachments</strong><small>{new Set(attachments.map(a=>a.muscle.id)).size} muscles linked to this bone</small></span><ArrowUpRight size={17}/></button></div>}
 {mode==='landmarks'&&<><p className="study-help">Select a named region to inspect its relationships. Colors distinguish anatomical categories.</p><div className="landmark-legend">{['Head','Fossa','Tubercle','Border'].map(n=>{const f=landmarkFamily(n);return <span key={n}><i style={{background:f.color}}/>{f.label}</span>;})}</div>{mapped.length<landmarks.length&&<p className="coverage-note"><Info size={15}/>{mapped.length} of {landmarks.length} surface regions available. List colors are a study key, not a substitute for segmented bone surfaces.</p>}<div className="bone-study-list">{landmarks.map(e=>{const f=landmarkFamily(e.name);return <button key={e.id} onClick={()=>onSelect(e.id)}><span className="landmark-swatch" style={{background:f.color}}/><span><strong>{e.name.replace(bone.name+' · ','')}</strong><small>{f.label}</small></span><ArrowUpRight size={15}/></button>;})}</div></>}
 {mode==='attachments'&&<><Tabs value={kind} onValueChange={v=>setKind(v as typeof kind)}><TabsList className="attachment-kind"><TabsTrigger value="both">O + I</TabsTrigger><TabsTrigger value="origin">Origin</TabsTrigger><TabsTrigger value="insertion">Insertion</TabsTrigger></TabsList></Tabs><p className="coverage-note"><Info size={15}/>{bonePatches(boneId,kind).length} eligible surface areas. Named attachments remain available below; unreviewed areas are not painted onto the bone.</p><div className="bone-study-list">{attachments.map(a=><button key={a.attachment.id+a.muscle.id} onClick={()=>onSelect(a.muscle.id)}><span className={'attachment-tag '+a.kind}>{a.kind==='origin'?'O':'I'}</span><span><strong>{a.muscle.name}</strong><small>{a.attachment.site}</small></span><ArrowUpRight size={15}/></button>)}{!attachments.length&&<p className="study-help">No {kind==='both'?'muscle':kind} attachments are mapped for this bone. Tendon and ligament relationships may still be listed under Connections.</p>}</div></>}
 {mode==='overview'&&bone.relations.some(r=>r.type==='clinical correlation')&&<div className="bone-clinical"><h3>Clinical relationships</h3>{bone.relations.filter(r=>r.type==='clinical correlation').map(r=><button key={r.targetId} onClick={()=>onSelect(r.targetId)}>{nameOf(r.targetId)}<ArrowUpRight size={14}/></button>)}</div>}
 {['ligaments','joints','neurovascular','clinical'].includes(mode)&&<div className="bone-study-list">{(()=>{const linked=boneRelations(boneId,mode==='ligaments'?['ligament']:mode==='joints'?['joint']:mode==='clinical'?['clinical']:['nerve','artery','vein']);return linked.length?linked.map(e=><button key={e.id} onClick={()=>onSelect(e.id)}><span><strong>{e.name}</strong><small>{e.description}</small></span><ArrowUpRight size={15}/></button>):<p className="study-help">No relationship is mapped in this category yet.</p>;})()}</div>}
 </section>;
}
