'use client';
import { useState } from 'react';
import { ArrowUpRight,Info } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger } from '@atlas/components/ui/tabs';
import { nameOf,attachmentAssets } from '@atlas/lib/anatomy';
import type { Muscle } from '@atlas/lib/anatomy/schema';
export default function MuscleStudy({muscle:m,onSelect,onAction}:{muscle:Muscle;onSelect:(id:string)=>void;onAction:(action:string,id:string)=>void}){
 const [view,setView]=useState('overview');
 const links=(ids:string[])=><div className="study-link-list">{ids.map(id=><button key={id} onClick={()=>onSelect(id)}>{nameOf(id)}<ArrowUpRight size={15}/></button>)}</div>;
 function choose(v:string){setView(v);if(['origin','insertion','both'].includes(v))onAction(v,m.id);}
 const tabs=[['overview','Overview'],['origin','O'],['insertion','I'],['both','O + I'],['action','Action'],['nerve','Nerve'],['vessel','Vessel'],...(m.lymphaticRelevance?[['lymph','Lymph']]:[]),['joints','Joints'],['clinical','Clinical']];
 return <section className="muscle-study"><Tabs value={view} onValueChange={choose}><TabsList className="muscle-view-tabs">{tabs.map(([id,label])=><TabsTrigger key={id} value={id} aria-label={id==='origin'?'Show origin':id==='insertion'?'Show insertion':id==='both'?'Show origin and insertion':label}>{label}</TabsTrigger>)}</TabsList></Tabs>
 {view==='overview'?<><p className="compartment-line">{m.compartment} · {m.layer}</p><p className="muscle-function">{m.functionalRole}</p><dl><div className="anatomy-fact"><dt>Origin</dt><dd>{m.origins.map(a=><p key={a.id}>{a.site}</p>)}</dd></div><div className="anatomy-fact"><dt>Insertion</dt><dd>{m.insertions.map(a=><p key={a.id}>{a.site}</p>)}</dd></div><div className="anatomy-fact"><dt>Innervation · {m.rootValues.join(' / ')}</dt><dd>{links(m.nerveIds)}</dd></div><div className="anatomy-fact"><dt>Blood supply</dt><dd>{links(m.arteryIds)}</dd></div></dl></>:['origin','insertion','both'].includes(view)?<><div className="attachment-readout">{(['origin','insertion'] as const).filter(k=>view==='both'||view===k).map(k=><section key={k}><h3><span className={'attachment-tag '+k}>{k==='origin'?'O':'I'}</span>{k==='origin'?'Origin':'Insertion'}</h3>{m[k==='origin'?'origins':'insertions'].map(a=><div key={a.id}><p>{a.site}</p>{links([...new Set([...a.landmarkIds,...a.boneIds])])}</div>)}</section>)}</div><p className="coverage-note"><Info size={15}/>{attachmentAssets(m.id,view as 'origin'|'insertion'|'both').length} source-mapped attachment surfaces. These show the source atlas regions; independent anatomical review is pending.</p></>:view==='action'?<><h3>Primary actions</h3>{links(m.movementIds)}{!!m.secondaryActions.length&&<><h3>Secondary actions</h3><p>{m.secondaryActions.join('; ')}</p></>}<h3>Synergists</h3>{links(m.synergistIds)}<h3>Antagonists</h3>{links(m.antagonistIds)}</>:view==='nerve'?<><h3>Innervation · {m.rootValues.join(' / ')}</h3>{links(m.nerveIds)}<p className="study-help">Choose a nerve to trace its contributing roots, branches and motor targets.</p></>:view==='vessel'?<><h3>Main arterial supply</h3>{links(m.arteryIds)}<p className="study-help">Choose a vessel to follow its proximal source and distal branches.</p></>:view==='lymph'&&m.lymphaticRelevance?<><h3>Regional lymphatic context</h3><p>{m.lymphaticRelevance.note}</p>{links([m.lymphaticRelevance.contextId])}</>:view==='joints'?<><h3>Related joints</h3>{links(m.jointIds)}</>:view==='clinical'?<><h3>Clinical correlations</h3>{m.clinicalIds.length?links(m.clinicalIds):<p className="study-help">No specific clinical case is linked to this muscle yet.</p>}</>:null}
 </section>;
}
