'use client';
import { entities, assets, byId, nameOf, muscle, attachmentAssets } from '@atlas/lib/anatomy';
import type { ViewState } from '@atlas/lib/state/viewer';
import { Slider } from '@atlas/components/ui/slider';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@atlas/components/ui/select';
import { Tabs,TabsList,TabsTrigger } from '@atlas/components/ui/tabs';
import { Play,Pause,RotateCcw,Info,Focus } from 'lucide-react';
import { motionIds,poseIds } from '@atlas/lib/anatomy/demonstrations';
interface Props{state:ViewState;patch:(s:Partial<ViewState>)=>void;onSelect:(id:string)=>void;progress:number;}
export function MovementControls({state:s,patch,onSelect,progress}:Props){const m=byId.get(s.movementId)!;const available=motionIds.has(m.id);return <div className="study-console"><div className="console-heading"><span className="eyebrow">MOVEMENT LAB</span><Select value={s.movementId} onValueChange={id=>{patch({movementId:id,playing:false,progress:0});onSelect(id);}}><SelectTrigger className="console-select"><SelectValue/></SelectTrigger><SelectContent>{entities.filter(e=>e.system==='movement').map(e=><SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>)}</SelectContent></Select></div>
 {available?<><div className="playback"><button className="play-button" aria-label={s.playing?'Pause movement':'Play movement'} onClick={()=>patch({playing:!s.playing,progress})}>{s.playing?<Pause size={18}/>:<Play size={18}/>}</button><Slider aria-label="Movement progress" value={[s.playing?progress*100:s.progress*100]} min={0} max={100} step={1} onValueChange={([v])=>patch({progress:v/100,playing:false})}/><span>{Math.round((s.playing?progress:s.progress)*100)}%</span><button className="icon-button" aria-label="Reset movement" onClick={()=>patch({playing:false,progress:0})}><RotateCcw size={17}/></button></div><p className="console-note">Illustrative bone motion · rig review pending. Soft tissues are hidden during motion.</p></>:<div className="pending-inline"><Info size={16}/><p>This movement is mapped in the atlas. Its anatomically reviewed animation is not yet available.</p></div>}
 {m.id==='shoulder-abduction'&&<div className="rhythm-note"><span>SCAPULOHUMERAL RHYTHM</span><p>Supraspinatus + deltoid, with upward rotation by serratus anterior and trapezius. The often-taught 2:1 ratio is an approximation; rhythm varies through elevation.</p></div>}
 </div>;}
export function ClinicalControls({state:s,patch,onSelect,progress}:Props){const c=byId.get(s.clinicalId)!;const specimen=assets.some(a=>a.role==='clinical-specimen'&&a.entityId===c.id);const available=poseIds.has(c.id)||specimen;return <div className="study-console"><div className="console-heading"><span className="eyebrow">CLINICAL ANATOMY</span><Select value={s.clinicalId} onValueChange={id=>{patch({clinicalId:id,clinicalLevel:id==='ulnar-claw'?'distal-ulnar':'radial-groove',abnormal:false,progress:0,playing:false});onSelect(id);}}><SelectTrigger className="console-select"><SelectValue/></SelectTrigger><SelectContent>{entities.filter(e=>e.system==='clinical').map(e=><SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>)}</SelectContent></Select></div>
 {available?<><Tabs value={s.abnormal?'abnormal':'normal'} onValueChange={v=>patch({abnormal:v==='abnormal',progress:v==='abnormal'?1:0,playing:false})}><TabsList className="comparison-tabs"><TabsTrigger value="normal">Reference specimen</TabsTrigger><TabsTrigger value="abnormal">{c.id==='hand-of-benediction'?'Attempt a fist':specimen?'Pathological specimen':'Abnormal posture'}</TabsTrigger></TabsList></Tabs>
 {(c.id==='wrist-drop'||c.id==='ulnar-claw')&&<Select value={s.clinicalLevel} onValueChange={clinicalLevel=>patch({clinicalLevel})}><SelectTrigger><SelectValue placeholder="Lesion level"/></SelectTrigger><SelectContent>{(c.id==='wrist-drop'?[['axilla','Axillary level'],['radial-groove','Radial groove'],['pin','Posterior interosseous nerve']]:[['distal-ulnar','Distal ulnar lesion'],['proximal-ulnar','Proximal ulnar lesion']]).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select>}
 {c.id==='hand-of-benediction'&&s.abnormal&&<button className="primary-button" onClick={()=>patch({playing:!s.playing,progress})}>{s.playing?<Pause size={16}/>:<Play size={16}/>}Attempt finger flexion</button>}
 <p className="console-note">{specimen?'Different source specimens; not paired patient scans. Source pathology is preserved. Laterality and independent review are pending.':'Illustrative bone posture · clinical rig review pending.'}</p></>:<div className="pending-inline"><Info size={16}/><p>A reviewed 3D model is still required for this case. The shoulder specimen is general atlas context, not a visualization of this condition.</p></div>}
 </div>;}
export function AttachmentControls({state:s,onSelect,patch}:Props){const kind=s.attachmentKind;const setKind=(kind:string)=>patch({attachmentKind:kind as ViewState['attachmentKind']});const selected=byId.get(s.selectedId??'');const m=selected?.system==='muscle'?muscle(selected):null;return <div className="attachment-console"><span className="eyebrow">ATTACHMENT STUDY</span><Select value={m?.id??''} onValueChange={onSelect}><SelectTrigger><SelectValue placeholder="Choose a muscle"/></SelectTrigger><SelectContent>{entities.filter(e=>e.system==='muscle').map(e=><SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>)}</SelectContent></Select>
 <Tabs value={kind} onValueChange={setKind}><TabsList className="comparison-tabs"><TabsTrigger value="origin">Origin</TabsTrigger><TabsTrigger value="insertion">Insertion</TabsTrigger><TabsTrigger value="both">Both</TabsTrigger></TabsList></Tabs>
 <div className="attachment-scroll">{m&&[['origin',m.origins],['insertion',m.insertions]].filter(([k])=>kind==='both'||k===kind).map(([k,items])=><div key={k as string} className={'attachment-group '+k}><h3><span/>{k as string}</h3>{(items as typeof m.origins).map(a=><div key={a.id} className="attachment-site"><p>{a.site}</p>{a.boneIds.length>0&&<div className="related-chips">{a.boneIds.map(id=><button key={id} onClick={()=>patch({focusId:id,focusTick:s.focusTick+1})}><Focus size={12}/>{nameOf(id)}</button>)}</div>}</div>)}</div>)}</div>
 <div className="attachment-coverage"><strong>{attachmentAssets(m?.id??'',kind).length} source surfaces shown</strong><p>Mint = origin · rose = insertion. Source surfaces use matching source bones. Coverage is partial; independent anatomical validation is pending. Sites without a surface provide bone context only.</p></div></div>;}
