import {useEffect, useRef, useState, type PointerEvent} from 'react';
import {Document, Page, pdfjs} from 'react-pdf';
import {Link} from 'wouter';
import {Upload, Sparkles, ScanLine, Send, ChevronLeft, ChevronRight, BookOpen, X, MessageCircle, ListChecks, Network, Box, StickyNote} from 'lucide-react';
import {readStudy, writeStudy, studyRequest} from '../lib/study-store';
import {demoSlides, demoResults} from '../lib/lecture-demo';
import anatomy from '@atlas/lib/anatomy/data/database.json';

type Explanation={source_mode?:string;explanation:string;high_yield:string[];terms:{term:string;meaning:string}[];clarifications:string[];mechanism:{label:string;source_quote:string}[];questions:{question:string;options:string[];correct_index:number;explanations:string[];source_quote:string}[];source_quotes:string[]};
type Turn={role:'user'|'assistant';content:string;selection?:string};
type Lecture={demo?:boolean;name:string;file?:File;slides:string[];page:number;results:Record<number,Explanation>;answers:Record<string,number>;notes:Record<number,string>;drafts?:Record<number,string>;modes?:Record<number,string>;history?:Record<number,Explanation[]>;conversations?:Record<number,Turn[]>};
type Region={x:number;y:number;w:number;h:number};
type Tab='explain'|'quiz'|'visual'|'atlas'|'notes';
const initial:Lecture={name:'',slides:[],page:1,results:{},answers:{},notes:{}};

export function Lectures(){
 const [lecture,setLecture]=useState<Lecture>(initial);
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [pasted,setPasted]=useState(''),[question,setQuestion]=useState(''),[selection,setSelection]=useState(''),[region,setRegion]=useState<Region|null>(null),[drawing,setDrawing]=useState(false);
 const [tab,setTab]=useState<Tab>('explain'),[width,setWidth]=useState(640),[saved,setSaved]=useState(''),[step,setStep]=useState(0);
 const slideRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),fileRef=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null),start=useRef<{x:number;y:number}|null>(null),inFlight=useRef(false),generation=useRef(0),endRef=useRef<HTMLDivElement>(null);
 const page=lecture.page,text=lecture.slides[page-1]||'',result=lecture.results[page],turns=lecture.conversations?.[page]||[];
 useEffect(()=>{let active=true;readStudy<Lecture>('lecture').then(v=>{if(active){if(v)setLecture(v);setReady(true);}}).catch(()=>{if(active){setError('تعذر فتح الحفظ المحلي.');setReady(true);}});return()=>{active=false;generation.current++;controller.current?.abort();};},[]);
 useEffect(()=>{if(!ready)return;writeStudy('lecture',lecture).then(()=>setSaved('محفوظة على جهازك')).catch(()=>setSaved('تعذر الحفظ المحلي'));},[lecture,ready]);
 useEffect(()=>{setQuestion(lecture.drafts?.[page]||'');setSelection('');setRegion(null);setDrawing(false);setStep(0);setError('');},[page,lecture.name]);
 useEffect(()=>{const el=slideRef.current;if(!el)return;const observer=new ResizeObserver(entries=>setWidth(Math.max(240,Math.floor(entries[0].contentRect.width))));observer.observe(el);return()=>observer.disconnect();},[ready,lecture.slides.length]);
 useEffect(()=>{endRef.current?.scrollIntoView({block:'nearest'});},[turns.length,busy]);
 function replaceLecture(next:Lecture){generation.current++;setLecture(next);setQuestion('');setSelection('');setRegion(null);setTab('explain');setError('');}
 function updateQuestion(value:string){setQuestion(value);setLecture(v=>({...v,drafts:{...v.drafts,[page]:value}}));}
 async function upload(file?:File){if(!file||inFlight.current)return;setError('');if(file.size>30*1024*1024){setError('الحد الأقصى 30 MB.');return;}setLoading(true);try{
  if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;try{if(pdf.numPages>300)throw new Error('الحد الأقصى 300 شريحة.');const slides:string[]=[];for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n);const content=await p.getTextContent();slides.push(content.items.map(x=>'str'in x?x.str+(x.hasEOL?'\n':' '):'').join(''));}replaceLecture({...initial,name:file.name,file,slides});}finally{await pdf.destroy();}}
  else if(file.name.toLowerCase().endsWith('.txt'))replaceLecture({...initial,name:file.name,slides:(await file.text()).split(/\n\s*---\s*\n/)});
  else throw new Error('افتحي PDF أو TXT. صدّري PowerPoint كملف PDF.');
 }catch(e){setError(e instanceof Error?e.message:'تعذر فتح الملف.');}finally{setLoading(false);if(fileRef.current)fileRef.current.value='';}}
 function selectText(){if(drawing)return;const selected=window.getSelection();if(selected?.anchorNode&&slideRef.current?.contains(selected.anchorNode)&&selected.focusNode&&slideRef.current.contains(selected.focusNode)){const value=selected.toString().trim().slice(0,1500);if(value){setSelection(value);setRegion(null);}}}
 function point(e:PointerEvent<HTMLDivElement>){const r=e.currentTarget.getBoundingClientRect();return {x:Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)),y:Math.min(1,Math.max(0,(e.clientY-r.top)/r.height))};}
 function beginRegion(e:PointerEvent<HTMLDivElement>){if(!drawing)return;e.currentTarget.setPointerCapture(e.pointerId);start.current=point(e);setRegion(null);setSelection('');}
 function moveRegion(e:PointerEvent<HTMLDivElement>){if(!start.current)return;const p=point(e),s=start.current;setRegion({x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),w:Math.abs(p.x-s.x),h:Math.abs(p.y-s.y)});}
 function finishRegion(e:PointerEvent<HTMLDivElement>){if(!start.current)return;moveRegion(e);const p=point(e),s=start.current;start.current=null;if(Math.abs(p.x-s.x)<.02||Math.abs(p.y-s.y)<.02)setRegion(null);else setDrawing(false);}
 function slideImage(){const source=canvasRef.current;if(!lecture.file||!source?.width||!source.height)return undefined;const r=region||{x:0,y:0,w:1,h:1};const scale=Math.min(1,1400/Math.max(source.width*r.w,source.height*r.h));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(source.width*r.w*scale));canvas.height=Math.max(1,Math.round(source.height*r.h*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('تعذر قراءة صورة السلايد.');ctx.drawImage(source,source.width*r.x,source.height*r.y,source.width*r.w,source.height*r.h,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.82);}
 async function explain(prompt?:string,target:Tab='explain'){
  if(inFlight.current||loading)return;inFlight.current=true;setBusy(true);setError('');setTab(target);const id=generation.current,requestPage=page;const message=prompt?.trim()||(region?'اشرح الرسم المحدد وعلاقته بالسلايد':selection?'اشرح هذا المقطع: '+selection:'اشرح السلايد ببساطة، خطوة بخطوة');const ac=new AbortController();controller.current=ac;const timer=setTimeout(()=>ac.abort(),285000);
  try{const image=slideImage();if(!text.trim()&&!image)throw new Error('انتظري ظهور السلايد، ثم اطلبي الشرح.');const data=await studyRequest('lecture',{source_mode:lecture.modes?.[page]||'lecture_only',slide:text.slice(0,18000),image,selection,region:!!region,page,title:lecture.name,question:message.slice(0,2000),conversation:turns.slice(-8).map(({role,content})=>({role,content:content.slice(0,12000)})),context:lecture.slides.slice(Math.max(0,page-2),page+1).map(t=>t.slice(0,3000))},ac.signal);
   if(id!==generation.current)return;const lesson:Explanation=data.lesson;setLecture(v=>({...v,results:{...v.results,[requestPage]:{...lesson,source_mode:lecture.modes?.[requestPage]||'lecture_only'}},conversations:{...v.conversations,[requestPage]:[...(v.conversations?.[requestPage]||[]),{role:'user',content:message,selection:region?'جزء من الرسم':selection||undefined},{role:'assistant',content:lesson.explanation}]},drafts:{...v.drafts,[requestPage]:''},answers:Object.fromEntries(Object.entries(v.answers).filter(([k])=>!k.startsWith(requestPage+':')))}));setQuestion('');setSelection('');setRegion(null);setStep(0);
  }catch(e){if(id===generation.current)setError(ac.signal.aborted?'توقف الطلب. يمكنك المحاولة مجددًا؛ سلايدك ومحادثتك محفوظان.':e instanceof Error?e.message:'تعذر الشرح.');}finally{clearTimeout(timer);inFlight.current=false;setBusy(false);}
 }
 const links=(anatomy.entities as {id:string;name:string;aliases:string[];system:string}[]).filter(e=>['bone','muscle','nerve','artery','vein','joint','ligament'].includes(e.system)&&[e.name,...e.aliases].some(n=>n.length>4&&(text+' '+(result?.explanation||'')).toLowerCase().includes(n.toLowerCase()))).slice(0,16);
 function openTab(next:Tab){setTab(next);if((next==='quiz'||next==='visual')&&!result&&!busy)void explain(next==='quiz'?'اختبر فهمي لهذا السلايد بأسئلة مع شرح سبب كل خيار':'وضّح العلاقات أو تسلسل الآلية الموجودة في هذا السلايد',next);}
 if(!ready)return <section className="study-page" role="status">فتح مساحة الدراسة…</section>;
 return <section className="study-page lecture-studio" dir="rtl">
  <header className="studio-heading"><div><span className="study-badge">LECTURE EXPLAINER</span><h1>افهميها، سلايد بسلايد.</h1></div><small>{saved}</small>{lecture.slides.length>0&&<button disabled={busy||loading} onClick={()=>fileRef.current?.click()}><Upload size={16}/>تغيير المحاضرة</button>}</header>
  <input className="sr-only" ref={fileRef} type="file" accept="application/pdf,.pdf,text/plain,.txt" aria-label="فتح محاضرة" disabled={busy||loading} onChange={e=>void upload(e.target.files?.[0])}/>
  {!lecture.slides.length?<div className="lecture-welcome"><BookOpen size={40}/><h2>محاضرتك أمامك. والشرح معها.</h2><p>افتحي محاضرة، حددي ما يحتاج توضيحًا، وكمّلي بسؤالك.</p><button className="primary" disabled={loading} onClick={()=>fileRef.current?.click()}><Upload size={18}/>{loading?'جاري فتح المحاضرة…':'افتحي محاضرة PDF'}</button><small>PDF أو TXT · حتى 30 MB</small><details><summary>لصق نص بدل الملف</summary><textarea aria-label="نص المحاضرة" rows={5} value={pasted} onChange={e=>setPasted(e.target.value)} placeholder="افصلي السلايدات بسطر يحتوي ---"/><button disabled={!pasted.trim()||loading} onClick={()=>{replaceLecture({...initial,name:'محاضرة نصية',slides:pasted.split(/\n\s*---\s*\n/)});setPasted('');}}>افتحي النص</button></details><button className="demo-link" disabled={loading} onClick={()=>replaceLecture({...initial,demo:true,name:'Radial nerve',slides:demoSlides,results:demoResults})}>استكشفي مثالًا جاهزًا: Radial nerve</button><small>المثال مادة تعليمية مُعدّة مسبقًا، وليس شرح AI لمحاضرتك.</small></div>:<>
   <div className="studio-toolbar"><strong dir="auto">{lecture.name}</strong><div className="slide-pagination"><button aria-label="السلايد السابق" disabled={page===1||busy||loading} onClick={()=>setLecture(v=>({...v,page:page-1}))}><ChevronRight size={18}/></button><label><span className="sr-only">رقم السلايد</span><select disabled={busy||loading} value={page} onChange={e=>setLecture(v=>({...v,page:Number(e.target.value)}))}>{lecture.slides.map((_,i)=><option key={i} value={i+1}>{i+1} / {lecture.slides.length}</option>)}</select></label><button aria-label="السلايد التالي" disabled={page===lecture.slides.length||busy||loading} onClick={()=>setLecture(v=>({...v,page:page+1}))}><ChevronLeft size={18}/></button></div></div>
   <div className="studio-grid"><div className="slide-workspace"><div className="slide-actions"><span>حددي نصًا {lecture.file?'أو رسمًا':''} لشرحه</span>{lecture.file&&<button aria-pressed={drawing} disabled={busy||loading} onClick={()=>{setDrawing(!drawing);setRegion(null);}}><ScanLine size={16}/>{drawing?'إلغاء التحديد':'تحديد رسم'}</button>}<button className="primary" disabled={busy||loading} onClick={()=>void explain()}><Sparkles size={16}/>{selection||region?'اشرح المحدد':'Explain'}</button></div>
    <div ref={slideRef} className="slide-stage" onPointerUp={selectText} onKeyUp={selectText}>{lecture.file?<Document file={lecture.file} loading="تحميل السلايد…" error="تعذر عرض PDF. جرّبي فتح الملف مجددًا."><div className="pdf-slide-wrap"><Page key={page} pageNumber={page} width={width} canvasRef={canvasRef} renderTextLayer renderAnnotationLayer={false}/>{drawing&&<div className="region-draw" aria-label="اسحبي لتحديد الرسم" onPointerDown={beginRegion} onPointerMove={moveRegion} onPointerUp={finishRegion} onPointerCancel={()=>{start.current=null;setRegion(null);}}/>}{region&&<div className="selected-region" style={{left:region.x*100+'%',top:region.y*100+'%',width:region.w*100+'%',height:region.h*100+'%'}}/>}</div></Document>:<div className="text-slide"><span>SLIDE {page.toString().padStart(2,'0')}</span><pre dir="auto">{text}</pre></div>}</div>
    {(selection||region)&&<div className="selection-bar"><span dir="auto">{region?'الرسم المحدد جاهز للشرح':selection}</span><button aria-label="إلغاء التحديد" onClick={()=>{setSelection('');setRegion(null);}}><X size={15}/></button><button disabled={busy} onClick={()=>void explain()}>اشرح الآن</button></div>}
    <div className="slide-footer"><span>{lecture.demo?'مثال مُعد مسبقًا': 'يبقى الملف على جهازك؛ عند الشرح يُرسل نص السلايد وصورته أو الجزء المحدد.'}</span><details><summary>خريطة السلايدات</summary><nav className="lecture-map" aria-label="خريطة المحاضرة">{lecture.slides.map((s,i)=><button disabled={busy||loading} aria-current={page===i+1?'page':undefined} className={page===i+1?'active':''} key={i} onClick={()=>setLecture(v=>({...v,page:i+1}))}>{i+1}. {s.trim().split('\n')[0].slice(0,55)||'سلايد مصوّر'}</button>)}</nav></details></div>
   </div><aside className="tutor-panel" aria-label="رفيق الدراسة"><nav className="tutor-tabs" aria-label="أدوات الدراسة">{([{id:'explain',label:'الشرح',Icon:MessageCircle},{id:'quiz',label:'Quiz',Icon:ListChecks},{id:'visual',label:'Visual',Icon:Network},{id:'atlas',label:'3D',Icon:Box},{id:'notes',label:'ملاحظاتي',Icon:StickyNote}] as const).map(({id,label,Icon})=><button key={id} aria-pressed={tab===id} disabled={loading} onClick={()=>openTab(id)}><Icon size={17}/>{label}</button>)}</nav>
    <div className="tutor-content" aria-live="polite">
     {tab==='explain'&&<>{!turns.length&&!result&&<div className="tutor-empty"><Sparkles size={28}/><h2>وش تبغين تفهمين؟</h2><p>اضغطي Explain، أو حددي كلمة، جملة، أو رسم في السلايد.</p><button disabled={busy} onClick={()=>void explain('اشرح الفكرة الأساسية ببساطة')}>بسّطي الفكرة</button><button disabled={busy} onClick={()=>void explain('اشرح السلايد خطوة بخطوة')}>خطوة بخطوة</button></div>}{!turns.length&&result&&<article className="tutor-answer"><small>{lecture.demo?'شرح المثال المُعد مسبقًا':'الشرح المحفوظ'}</small><p className="preserve" dir="auto">{result.explanation}</p></article>}{turns.map((turn,i)=><article key={i} className={'tutor-turn '+turn.role}><strong>{turn.role==='user'?'أنتِ':'MedNote'}</strong>{turn.selection&&<small>{turn.selection}</small>}<p className="preserve" dir="auto">{turn.content}</p></article>)}{result&&<><div className="followup-chips"><button disabled={busy} onClick={()=>void explain('بسّطي شرحك السابق أكثر، وركزي على النقطة التي سألت عنها')}>أبسط أكثر</button><button disabled={busy} onClick={()=>void explain('لماذا؟ وضّحي العلاقة في الشرح السابق من السلايد')}>ليش؟</button><button onClick={()=>openTab('quiz')}>اختبريني</button></div>{result.clarifications.length>0&&<aside className="study-warning"><strong>توضيح خارج المحاضرة</strong>{result.clarifications.map((s,i)=><p key={i}>{s}</p>)}</aside>}<details><summary>النقاط والمصطلحات والمصدر</summary><ul>{result.high_yield.map((s,i)=><li key={i}>{s}</li>)}</ul>{result.terms.map((t,i)=><p key={i}><button disabled={busy} onClick={()=>void explain('اشرح المصطلح: '+t.term)}>{t.term}</button> {t.meaning}</p>)}{result.source_quotes.map((s,i)=><blockquote key={i} dir="auto">{s}</blockquote>)}</details></> }</>}
     {tab==='quiz'&&<><h2>اختبري فهمك</h2>{result?.questions.map((q,i)=>{const chosen=lecture.answers[page+':'+i];return <fieldset key={i} className="checkpoint"><legend>{q.question}</legend>{q.options.map((o,j)=><button key={j} disabled={chosen!==undefined} className={chosen===j?'selected':''} onClick={()=>setLecture(v=>({...v,answers:{...v.answers,[page+':'+i]:j}}))}>{o}</button>)}{chosen!==undefined&&<div className="study-feedback"><strong>{chosen===q.correct_index?'إجابة صحيحة':'راجعي هذه النقطة'}</strong>{q.options.map((o,j)=><p key={j}>{j===q.correct_index?'✓':'—'} {o}: {q.explanations[j]}</p>)}{q.source_quote&&<blockquote dir="auto">{q.source_quote}</blockquote>}<button onClick={()=>setLecture(v=>({...v,answers:Object.fromEntries(Object.entries(v.answers).filter(([k])=>k!==page+':'+i))}))}>أعيد المحاولة</button></div>}</fieldset>;})}{result&&!result.questions.length&&<p>محتوى هذا السلايد لا يكفي لسؤال موثوق.</p>}</>}
     {tab==='visual'&&<><h2>الفكرة أمامك</h2>{result?.mechanism.length?<><div className="visual-flow">{result.mechanism.map((s,i)=><button className={step===i?'current':''} key={i} onClick={()=>setStep(i)}><span>{i+1}</span>{s.label}</button>)}</div><p className="source-label">الخطوة {step+1} / {result.mechanism.length}</p>{result.mechanism[step]?.source_quote&&<blockquote dir="auto">{result.mechanism[step].source_quote}</blockquote>}<button onClick={()=>setStep(s=>(s+1)%result.mechanism.length)}>الخطوة التالية</button></>:<p>لا يوجد تسلسل آلية واضح في هذا السلايد. حددي الرسم نفسه لشرحه، أو استخدمي الشرح النصي.</p>}</>}
     {tab==='atlas'&&<><h2>استكشفي في 3D</h2><p>اختاري تركيبًا مرتبطًا بالسلايد. مكانك ومحادثتك يبقون محفوظين.</p><div className="anatomy-links">{links.map(e=><Link key={e.id} href={'/anatomy?structure='+encodeURIComponent(e.id)+'&from=lecture'}>{e.name} ↗</Link>)}{!links.length&&<><p>لم نجد تركيبًا مطابقًا تلقائيًا.</p><Link href="/anatomy?from=lecture">ابحثي داخل الأطلس ↗</Link></>}</div></>}
     {tab==='notes'&&<><h2>ملاحظاتي · سلايد {page}</h2><textarea aria-label="ملاحظاتي لهذا السلايد" rows={12} value={lecture.notes[page]||''} onChange={e=>setLecture(v=>({...v,notes:{...v.notes,[page]:e.target.value}}))} placeholder="اكتبي بطريقتك ما فهمتيه…"/></>}
     {busy&&<div className="tutor-loading" role="status"><Sparkles size={18}/><span>أقرأ السلايد وأجهّز الشرح…</span><button onClick={()=>controller.current?.abort()}>إيقاف</button></div>}{error&&<p role="alert" className="study-error">{error}</p>}<div ref={endRef}/>
    </div><form className="tutor-composer" onSubmit={e=>{e.preventDefault();if(question.trim())void explain(question);}}><div className="composer-row"><textarea aria-label="اسألي عن السلايد" rows={2} maxLength={2000} value={question} onChange={e=>updateQuestion(e.target.value)} placeholder="ما فهمت… اسألي وكمّلي النقاش" disabled={busy} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(question.trim())void explain(question);}}}/><button className="primary" type="submit" disabled={busy||loading||!question.trim()} aria-label="إرسال سؤال المتابعة"><Send size={18}/></button></div><details><summary>{lecture.modes?.[page]==='supplemental'?'مع توضيح إضافي منفصل':'من المحاضرة فقط'}</summary><label>مصدر الشرح<select disabled={busy} value={lecture.modes?.[page]||'lecture_only'} onChange={e=>setLecture(v=>({...v,modes:{...v.modes,[page]:e.target.value}}))}><option value="lecture_only">المحاضرة فقط</option><option value="supplemental">المحاضرة + توضيح إضافي منفصل</option></select></label></details></form>
   </aside></div>
  </>}{!lecture.slides.length&&error&&<p role="alert" className="study-error">{error}</p>}{loading&&lecture.slides.length>0&&<p role="status">جاري فتح المحاضرة الجديدة…</p>}
 </section>;
}
