import {useEffect, useRef, useState, type PointerEvent} from 'react';
import {Document, Page, pdfjs} from 'react-pdf';
import {Upload, Sparkles, ScanLine, Send, ChevronLeft, ChevronRight, BookOpen, X, MessageCircle, ListChecks, Network, StickyNote, } from 'lucide-react';
import {readStudy, writeStudy, studyRequest} from '../lib/study-store';
import {demoSlides, demoResults} from '../lib/lecture-demo';
import {LessonJourney} from '../components/study/LessonJourney';
import type {Explanation} from '../components/study/types';

type Turn={role:'user'|'assistant';content:string;selection?:string;lesson?:Explanation};
type StudyTool='explain'|'quiz'|'visual';
type Lecture={demo?:boolean;name:string;file?:File;slides:string[];page:number;results:Record<number,Explanation>;toolResults?:Record<number,Partial<Record<'quiz'|'visual',Explanation>>>;answers:Record<string,number>;notes:Record<number,string>;drafts?:Record<number,string>;modes?:Record<number,string>;history?:Record<number,Explanation[]>;conversations?:Record<number,Turn[]>};
type Region={x:number;y:number;w:number;h:number};
type Tab='explain'|'notes';
const initial:Lecture={name:'',slides:[],page:1,results:{},answers:{},notes:{}};

function LectureProgress({cancel}:{cancel:()=>void}){
 const [elapsed,setElapsed]=useState(0);
 useEffect(()=>{const started=Date.now();const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);return()=>clearInterval(timer);},[]);
 return <div className="tutor-loading" role="status"><Sparkles size={18}/><span>{elapsed<45?'أجهّز الشرح وأراجعه مع السلايد…':'تأخر الرد؛ ما زلت أراجع الطلب. يمكنك إيقافه دون فقد محتواك.'}<small style={{display:'block'}}>{elapsed} ثانية</small></span><button onClick={cancel}>إيقاف</button></div>;
}

export {LectureCourse as Lectures} from '../components/study/LectureCourse';

export function SourceLecture(){
 const [lecture,setLecture]=useState<Lecture>(initial);
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [pasted,setPasted]=useState(''),[question,setQuestion]=useState(''),[selection,setSelection]=useState(''),[region,setRegion]=useState<Region|null>(null),[drawing,setDrawing]=useState(false);
 const [imageUrl,setImageUrl]=useState(''),[mediaReady,setMediaReady]=useState(false);
 const imageRef=useRef<HTMLImageElement>(null);
 const lastAttempt=useRef<{message:string;target:StudyTool;selection:string;region:Region|null}|null>(null);
 const [tab,setTab]=useState<Tab>('explain'),[width,setWidth]=useState(640),[saved,setSaved]=useState('');
 const slideRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),fileRef=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null),start=useRef<{x:number;y:number}|null>(null),inFlight=useRef(false),generation=useRef(0),endRef=useRef<HTMLDivElement>(null);
 const isImage=!!lecture.file?.type.startsWith('image/');
 useEffect(()=>{setMediaReady(false);if(!lecture.file?.type.startsWith('image/')){setImageUrl('');return;}const url=URL.createObjectURL(lecture.file);setImageUrl(url);return()=>URL.revokeObjectURL(url);},[lecture.file]);
 useEffect(()=>{setMediaReady(false);},[lecture.page]);
 const page=lecture.page,text=lecture.slides[page-1]||'',result=lecture.results[page],turns=lecture.conversations?.[page]||[];
 useEffect(()=>{let active=true;readStudy<Lecture>('lecture').then(v=>{if(active){if(v)setLecture(v);setReady(true);}}).catch(()=>{if(active){setError('تعذر فتح الحفظ المحلي.');setReady(true);}});return()=>{active=false;generation.current++;controller.current?.abort();};},[]);
 useEffect(()=>{if(!ready)return;writeStudy('lecture',lecture).then(()=>setSaved('محفوظة على جهازك')).catch(()=>setSaved('تعذر الحفظ المحلي'));},[lecture,ready]);
 useEffect(()=>{setQuestion(lecture.drafts?.[page]||'');setSelection('');setRegion(null);setDrawing(false);setError('');lastAttempt.current=null;},[page,lecture.name]);
 useEffect(()=>{const el=slideRef.current;if(!el)return;const observer=new ResizeObserver(entries=>setWidth(Math.max(240,Math.floor(entries[0].contentRect.width))));observer.observe(el);return()=>observer.disconnect();},[ready,lecture.slides.length]);
 useEffect(()=>{const area=endRef.current?.parentElement;if(area&&busy)area.scrollTop=area.scrollHeight;},[turns.length,busy]);
 function replaceLecture(next:Lecture){generation.current++;lastAttempt.current=null;setLecture(next);setQuestion('');setSelection('');setRegion(null);setTab('explain');setError('');}
 function updateQuestion(value:string){setQuestion(value);setLecture(v=>({...v,drafts:{...v.drafts,[page]:value}}));}
 async function upload(file?:File){if(!file||inFlight.current)return;setError('');if(file.size>30*1024*1024){setError('الحد الأقصى 30 MB.');return;}setLoading(true);try{
  if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;try{if(pdf.numPages>300)throw new Error('الحد الأقصى 300 شريحة.');const slides:string[]=[];for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n);const content=await p.getTextContent();slides.push(content.items.map(x=>'str'in x?x.str+(x.hasEOL?'\n':' '):'').join(''));}replaceLecture({...initial,name:file.name,file,slides});}finally{await pdf.destroy();}}
  else if(['image/jpeg','image/png','image/webp'].includes(file.type))replaceLecture({...initial,name:file.name,file,slides:['']});
  else if(file.name.toLowerCase().endsWith('.txt'))replaceLecture({...initial,name:file.name,slides:(await file.text()).split(/\n\s*---\s*\n/)});
  else throw new Error('افتحي PDF أو صورة JPG/PNG/WebP أو TXT. صدّري PowerPoint كملف PDF.');
 }catch(e){setError(e instanceof Error?e.message:'تعذر فتح الملف.');}finally{setLoading(false);if(fileRef.current)fileRef.current.value='';}}
 function selectText(){if(drawing)return;const selected=window.getSelection();if(selected?.anchorNode&&slideRef.current?.contains(selected.anchorNode)&&selected.focusNode&&slideRef.current.contains(selected.focusNode)){const value=selected.toString().trim().slice(0,1500);if(value){setSelection(value);setRegion(null);}}}
 function point(e:PointerEvent<HTMLDivElement>){const r=e.currentTarget.getBoundingClientRect();return {x:Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)),y:Math.min(1,Math.max(0,(e.clientY-r.top)/r.height))};}
 function beginRegion(e:PointerEvent<HTMLDivElement>){if(!drawing)return;e.currentTarget.setPointerCapture(e.pointerId);start.current=point(e);setRegion(null);setSelection('');}
 function moveRegion(e:PointerEvent<HTMLDivElement>){if(!start.current)return;const p=point(e),s=start.current;setRegion({x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),w:Math.abs(p.x-s.x),h:Math.abs(p.y-s.y)});}
 function finishRegion(e:PointerEvent<HTMLDivElement>){if(!start.current)return;moveRegion(e);const p=point(e),s=start.current;start.current=null;if(Math.abs(p.x-s.x)<.02||Math.abs(p.y-s.y)<.02)setRegion({x:Math.max(0,Math.min(.75,p.x-.125)),y:Math.max(0,Math.min(.75,p.y-.125)),w:.25,h:.25});setDrawing(false);}
 function slideImage(crop:Region|null=null){const source=isImage?imageRef.current:canvasRef.current;if(!lecture.file||!source)return undefined;const sw=source instanceof HTMLImageElement?source.naturalWidth:source.width,sh=source instanceof HTMLImageElement?source.naturalHeight:source.height;if(!sw||!sh||!mediaReady)throw new Error('انتظري ظهور السلايد كاملًا، ثم اطلبي الشرح.');const r=crop||{x:0,y:0,w:1,h:1};const scale=Math.min(1,1600/Math.max(sw*r.w,sh*r.h));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(sw*r.w*scale));canvas.height=Math.max(1,Math.round(sh*r.h*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('تعذر قراءة صورة السلايد.');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(source,sw*r.x,sh*r.y,sw*r.w,sh*r.h,0,0,canvas.width,canvas.height);let encoded=canvas.toDataURL('image/jpeg',.82);if(encoded.length>1300000)encoded=canvas.toDataURL('image/jpeg',.6);if(encoded.length>1300000)throw new Error('الصورة كبيرة جدًا؛ افتحي نسخة أصغر منها.');return encoded;}

 async function explain(prompt?:string,target:StudyTool='explain',focus={selection,region}){
  if(inFlight.current||loading)return;inFlight.current=true;setBusy(true);setError('');setTab('explain');const id=generation.current,requestPage=page;const message=prompt?.trim()||(focus.region?'اشرح الرسم المحدد وعلاقته بالسلايد':focus.selection?'اشرح هذا المقطع: '+focus.selection:'اشرح السلايد ببساطة، خطوة بخطوة');lastAttempt.current={message,target,...focus};const ac=new AbortController();controller.current=ac;const timer=setTimeout(()=>ac.abort(),285000);
  try{const image=slideImage(),detail_image=focus.region?slideImage(focus.region):undefined;if(!text.trim()&&!image)throw new Error('انتظري ظهور السلايد، ثم اطلبي الشرح.');const data=await studyRequest('lecture',{requested_tool:target,source_mode:lecture.modes?.[page]||'lecture_only',slide:text.slice(0,18000),image,detail_image,selection:focus.selection,region:!!focus.region,region_bounds:focus.region||undefined,page,title:lecture.name,question:message.slice(0,2000),conversation:turns.slice(-8).map(({role,content,lesson})=>({role,content:(lesson?JSON.stringify({explanation:content,opening:lesson.opening,mechanism:lesson.mechanism,questions:lesson.questions,checkpoint:lesson.checkpoint,source_mode:lesson.source_mode}):content).slice(0,12000)})),context:lecture.slides.slice(Math.max(0,page-2),page+1).map(t=>t.slice(0,3000))},ac.signal);
   if(id!==generation.current)return;const lesson:Explanation={...data.lesson,id:crypto.randomUUID(),requested_tool:target,source_mode:lecture.modes?.[requestPage]||'lecture_only'};
   setLecture(v=>({...v,
    results:{...v.results,[requestPage]:target==='explain'||!v.results[requestPage]?lesson:v.results[requestPage]},
    toolResults:{...v.toolResults,[requestPage]:{
     ...(v.results[requestPage]?.questions.length?{quiz:v.results[requestPage]}:{}),
     ...(v.results[requestPage]?.mechanism.length?{visual:v.results[requestPage]}:{}),
     ...v.toolResults?.[requestPage],...(target==='explain'?{}:{[target]:lesson})}},
    conversations:{...v.conversations,[requestPage]:[...(v.conversations?.[requestPage]||[]),{role:'user',content:message,selection:focus.region?'جزء من الرسم':focus.selection||undefined},{role:'assistant',content:lesson.explanation,lesson}]},
    drafts:target==='explain'?{...v.drafts,[requestPage]:''}:v.drafts,
    answers:v.answers}));
   if(target==='explain')setQuestion('');setSelection('');setRegion(null);
  }catch(e){if(id===generation.current)setError(ac.signal.aborted?'توقف الطلب. يمكنك المحاولة مجددًا؛ سلايدك ومحادثتك محفوظان.':e instanceof Error?e.message:'تعذر الشرح.');}finally{clearTimeout(timer);inFlight.current=false;setBusy(false);}
 }
 function answer(key:string,value?:number){setLecture(v=>({...v,answers:value===undefined?Object.fromEntries(Object.entries(v.answers).filter(([k])=>k!==key)):{...v.answers,[key]:value}}));}
 function sourceMode(mode:string){setLecture(v=>({...v,modes:{...v.modes,[page]:mode}}));}
 if(!ready)return <section className="study-page" role="status">فتح مساحة الدراسة…</section>;
 return <section className="study-page lecture-studio" dir="rtl">
  <header className="studio-heading"><div><span className="study-badge">LECTURE EXPLAINER</span><h1>افهميها، سلايد بسلايد.</h1></div><small>{saved}</small>{lecture.slides.length>0&&<button disabled={busy||loading} onClick={()=>fileRef.current?.click()}><Upload size={16}/>تغيير المحاضرة</button>}</header>
  <input className="sr-only" ref={fileRef} type="file" accept="application/pdf,.pdf,image/jpeg,image/png,image/webp,text/plain,.txt" aria-label="فتح محاضرة" disabled={busy||loading} onChange={e=>void upload(e.target.files?.[0])}/>
  {!lecture.slides.length?<div className="lecture-welcome"><BookOpen size={40}/><h2>محاضرتك أمامك. والشرح معها.</h2><p>افتحي محاضرة، حددي ما يحتاج توضيحًا، وكمّلي بسؤالك.</p><button className="primary" disabled={loading} onClick={()=>fileRef.current?.click()}><Upload size={18}/>{loading?'جاري فتح المحاضرة…':'افتحي PDF أو صورة'}</button><small>PDF، صورة، أو TXT · حتى 30 MB</small><details><summary>لصق نص بدل الملف</summary><textarea aria-label="نص المحاضرة" rows={5} value={pasted} onChange={e=>setPasted(e.target.value)} placeholder="افصلي السلايدات بسطر يحتوي ---"/><button disabled={!pasted.trim()||loading} onClick={()=>{replaceLecture({...initial,name:'محاضرة نصية',slides:pasted.split(/\n\s*---\s*\n/)});setPasted('');}}>افتحي النص</button></details><button className="demo-link" disabled={loading} onClick={()=>replaceLecture({...initial,demo:true,name:'Radial nerve',slides:demoSlides,results:demoResults})}>استكشفي مثالًا جاهزًا: Radial nerve</button><small>المثال مادة تعليمية مُعدّة مسبقًا، وليس شرح AI لمحاضرتك.</small></div>:<>
   <div className="studio-toolbar"><strong dir="auto">{lecture.name}</strong><div className="slide-pagination"><button aria-label="السلايد السابق" disabled={page===1||busy||loading} onClick={()=>setLecture(v=>({...v,page:page-1}))}><ChevronRight size={18}/></button><label><span className="sr-only">رقم السلايد</span><select disabled={busy||loading} value={page} onChange={e=>setLecture(v=>({...v,page:Number(e.target.value)}))}>{lecture.slides.map((_,i)=><option key={i} value={i+1}>{i+1} / {lecture.slides.length}</option>)}</select></label><button aria-label="السلايد التالي" disabled={page===lecture.slides.length||busy||loading} onClick={()=>setLecture(v=>({...v,page:page+1}))}><ChevronLeft size={18}/></button></div></div>
   <div className="studio-grid"><div className="slide-workspace"><div className="slide-actions"><span>حددي نصًا {lecture.file?'أو رسمًا':''} لشرحه</span>{lecture.file&&<button aria-pressed={drawing} disabled={busy||loading} onClick={()=>{setDrawing(!drawing);setRegion(null);}}><ScanLine size={16}/>{drawing?'إلغاء التحديد':'تحديد رسم / نقطة'}</button>}<button className="primary" disabled={busy||loading} onClick={()=>void explain()}><Sparkles size={16}/>{selection||region?'اشرح المحدد':'اشرح'}</button></div>
    <div ref={slideRef} className="slide-stage" onPointerUp={selectText} onKeyUp={selectText}>{isImage?<div className="pdf-slide-wrap"><img ref={imageRef} src={imageUrl} alt="السلايد الحالي" onLoad={()=>setMediaReady(true)} onError={()=>setError('تعذر فتح الصورة. جرّبي صورة أخرى.')} style={{display:'block',width:'100%'}}/>{drawing&&<div className="region-draw" aria-label="اسحبي لتحديد الرسم" onPointerDown={beginRegion} onPointerMove={moveRegion} onPointerUp={finishRegion} onPointerCancel={()=>{start.current=null;setRegion(null);}}/>}{region&&<div className="selected-region" style={{left:region.x*100+'%',top:region.y*100+'%',width:region.w*100+'%',height:region.h*100+'%'}}/>}</div>:lecture.file?<Document file={lecture.file} loading="تحميل السلايد…" error="تعذر عرض PDF. جرّبي فتح الملف مجددًا."><div className="pdf-slide-wrap"><Page key={page} pageNumber={page} width={width} canvasRef={canvasRef} onRenderSuccess={()=>setMediaReady(true)} renderTextLayer renderAnnotationLayer={false}/>{drawing&&<div className="region-draw" aria-label="اسحبي لتحديد الرسم" onPointerDown={beginRegion} onPointerMove={moveRegion} onPointerUp={finishRegion} onPointerCancel={()=>{start.current=null;setRegion(null);}}/>}{region&&<div className="selected-region" style={{left:region.x*100+'%',top:region.y*100+'%',width:region.w*100+'%',height:region.h*100+'%'}}/>}</div></Document>:<div className="text-slide"><span>SLIDE {page.toString().padStart(2,'0')}</span><pre dir="auto">{text}</pre></div>}</div>
    {(selection||region)&&<div className="selection-bar"><span dir="auto">{region?'الرسم المحدد جاهز للشرح':selection}</span><button aria-label="إلغاء التحديد" onClick={()=>{setSelection('');setRegion(null);}}><X size={15}/></button><button disabled={busy} onClick={()=>void explain()}>اشرح الآن</button></div>}
    <div className="slide-footer"><span>{lecture.demo?'مثال مُعد مسبقًا': 'يبقى الملف على جهازك؛ يُرسل السلايد الحالي كاملًا مع النص أو الرسم المحدد لفهم السياق.'}</span><details><summary>خريطة السلايدات</summary><nav className="lecture-map" aria-label="خريطة المحاضرة">{lecture.slides.map((s,i)=><button disabled={busy||loading} aria-current={page===i+1?'page':undefined} className={page===i+1?'active':''} key={i} onClick={()=>setLecture(v=>({...v,page:i+1}))}>{i+1}. {s.trim().split('\n')[0].slice(0,55)||'سلايد مصوّر'}</button>)}</nav></details></div>
   </div><aside className="tutor-panel" aria-label="رفيق الدراسة">
    <nav className="tutor-tabs" aria-label="مساحة الدراسة"><button aria-pressed={tab==='explain'} onClick={()=>setTab('explain')}><MessageCircle size={17}/>رحلة الفهم</button><button aria-pressed={tab==='notes'} onClick={()=>setTab('notes')}><StickyNote size={17}/>ملاحظاتي</button></nav>
    <div className="lecture-source-mode"><label>مصدر الشرح<select aria-label="مصدر الشرح" disabled={busy} value={lecture.modes?.[page]||'lecture_only'} onChange={e=>sourceMode(e.target.value)}><option value="lecture_only">Lecture only · المحاضرة فقط</option><option value="supplemental">Lecture + additional explanation</option></select></label><small>يُطبّق على الطلب التالي؛ كل شرح محفوظ يحتفظ بوسم مصدره.</small></div>
    <div className="tutor-content" aria-busy={busy}>
     {tab==='explain'&&<>
      {!turns.length&&!result&&<div className="tutor-empty"><Sparkles size={28}/><h2>من السلايد إلى الفهم</h2><p>حددي كلمة أو رسمًا، أو اضغطي اشرح. ستظهر الفكرة والرسم وأسئلة التفكير هنا، مع بقاء السلايد أمامك.</p><button disabled={busy} onClick={()=>void explain()}>ابدئي رحلة الفهم</button></div>}
      {!turns.length&&result&&<><small>{lecture.demo?'مثال تعليمي مُعد مسبقًا':'الشرح المحفوظ'}</small><LessonJourney key={page+':saved'} lesson={result} slide={text} prefix={page+':saved'} answers={lecture.answers} onAnswer={answer} busy={busy} onAsk={q=>void explain(q)}/></>}
      {turns.map((turn,i)=>turn.role==='user'?<article key={i} className="tutor-turn user"><strong>أنتِ</strong>{turn.selection&&<small>{turn.selection}</small>}<p dir="auto">{turn.content}</p></article>:turn.lesson?<div key={turn.lesson.id||i} className="tutor-turn assistant">{i===turns.length-1?<LessonJourney lesson={turn.lesson} slide={text} prefix={page+':'+(turn.lesson.id||i)} answers={lecture.answers} onAnswer={answer} busy={busy} onAsk={q=>void explain(q)}/>:<details><summary>الشرح السابق · {turn.lesson.source_mode==='supplemental'?'مع إضافات موسومة':'من المحاضرة'}</summary><LessonJourney lesson={turn.lesson} slide={text} prefix={page+':'+(turn.lesson.id||i)} answers={lecture.answers} onAnswer={answer} busy={busy} onAsk={q=>void explain(q)}/></details>}</div>:<article key={i} className="tutor-turn assistant"><strong>MedNote</strong><p className="preserve" dir="auto">{turn.content}</p></article>)}
      {!!turns.length&&!turns.some(t=>t.lesson)&&result&&<LessonJourney key={page+':legacy'} lesson={result} slide={text} prefix={String(page)} answers={lecture.answers} onAnswer={answer} busy={busy} onAsk={q=>void explain(q)}/>}
      {(result||turns.length>0)&&<div className="followup-chips"><button disabled={busy} onClick={()=>void explain('بسّطي شرحك السابق أكثر، وركزي على النقطة التي سألت عنها')}>بسّطيها</button><button disabled={busy} onClick={()=>void explain('لماذا؟ وضحي السبب والآلية والنتيجة في سياق السلايد')}>لماذا؟</button><button disabled={busy} onClick={()=>void explain('اختبر فهمي بتطبيق من المحاضرة، واشرح المفهوم وسبب صحة الإجابة وخطأ البدائل','quiz')}><ListChecks size={14}/>اختبريني</button><button disabled={busy} onClick={()=>void explain('وضحي الفكرة برسم مناسب مع شرح كل خطوة نصيًا','visual')}><Network size={14}/>وضّحي بصريًا</button></div>}
     </>}
     {tab==='notes'&&<><h2>ملاحظاتي · سلايد {page}</h2><textarea aria-label="ملاحظاتي لهذا السلايد" rows={12} value={lecture.notes[page]||''} onChange={e=>setLecture(v=>({...v,notes:{...v.notes,[page]:e.target.value}}))} placeholder="اكتبي بطريقتك ما فهمتيه…"/></>}
     {busy&&<LectureProgress cancel={()=>controller.current?.abort()}/>}
     {error&&<div role="alert" className="study-error"><p>{error}</p>{lastAttempt.current&&<button disabled={busy} onClick={()=>{const retry=lastAttempt.current;if(retry)void explain(retry.message,retry.target,retry);}}>إعادة المحاولة</button>}</div>}<div ref={endRef}/>
    </div><form className="tutor-composer" onSubmit={e=>{e.preventDefault();if(question.trim())void explain(question);}}><div className="composer-row"><textarea aria-label="اسألي عن السلايد" rows={2} maxLength={2000} value={question} onChange={e=>updateQuestion(e.target.value)} placeholder="اسألي عن الفكرة… سياق السلايد محفوظ" disabled={busy} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(question.trim())void explain(question);}}}/><button className="primary" type="submit" disabled={busy||loading||!question.trim()} aria-label="إرسال سؤال المتابعة"><Send size={18}/></button></div></form>
   </aside></div>
  </>}{!lecture.slides.length&&error&&<p role="alert" className="study-error">{error}</p>}{loading&&lecture.slides.length>0&&<p role="status">جاري فتح المحاضرة الجديدة…</p>}
 </section>;
}
